title                    : "Junteng Liu"
name                     : &name "Junteng Liu"
description              : &description "Personal academic website of Junteng Liu, a PhD candidate at HKUST"
url                      : https://bugmaker00.github.io/LJT-Homepage
baseurl                  : ""
repository               : "bugmaker00/LJT-Homepage"
